mb_bench_url: "https://www.moonboard.com/Dashboard/GetBenchmarks"
mb_login_url: "https://moonboard.com/account/login"
mb_dashboard_url: "https://www.moonboard.com/Dashboard/Index"
mb_username: "viking_climber"
mb_password: "cRQM6JzNrS4U!h2"

mb_headers:
  Accept: "*/*"
  Accept-Encoding: "gzip, deflate, br"
  Accept-Language: "en-US,en;q=0.9"
  Connection: "keep-alive"
  Content-Length: "86"
  Content-Type: "application/x-www-form-urlencoded; charset=UTF-8"
  Cookie: "; _gid=GA1.2.2073676022.1688218032; _gat_gtag_UA_73435918_1=1; _MoonBoard=0E2fH6GqPgyiomVDUYgFAxmDFaVVRqjUm83FGfcp_x9HKEvuA6Zb_p8wWaDmXjFb7rtnSlB4XwZRt0r9Xdz4_teS90tz7pLFmCIu_ZvOEYED8POQoEhL557BzxsudxCOkspQGBY7uiblL-7Pu6fDxRoJzIzk3kwuhtpbS5jDHSaazWkdrpnHKfKA1_D1jrXkmMUql9fyxxDjHkO7UGuoL9hIfiMYtZU7_BzI631S0lzDsXeuXGU4EjTExWtv5rV5sjnyDpqnx81McltNcIPPnnDxpepUPGXHlYuPsZep3x0Pe5w9LRK6QeaUB3eIEDWm2UQmWa4UlJLzibs3xdRPO6sIctZWc9AT9QfBx2-Vxtgv1Tzjxz3cuUDqiDOtiJGb40i88knRYhh1DuzC4uvM7eGzr8SCRNp4HR3dnHDpsaD812OFeVpQx7N_IftfD7K10wRwv7u8XIi4dKsa6B06XcxFyjREanUTbo1Y8OtsOUX5ZlO62GxFZ_kypK95_vCfgwM6mCnV2YQRamH6pSMBJtvSU_QVtPcfj9Nvo-J_7IM; _ga_FB4RWZ3KKE=GS1.1.1688216867.2.1.1688218041.0.0.0; _ga=GA1.1.1475750838.1688218032"
  Origin: "https://www.moonboard.com"
  Referer: "https://www.moonboard.com/Dashboard/Index"
  sec-ch-ua: "Chromium\";v=\"112\", \"Google Chrome\";v=\"112\", \"Not:A-Brand\";v=\"99\""
  sec-ch-ua-mobile: "?0"
  sec-ch-ua-platform: "macOS"
  Sec-Fetch-Dest: "empty"
  Sec-Fetch-Mode: "cors"
  Sec-Fetch-Site: "same-origin"
  User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
  X-Requested-With: "XMLHttpRequest"

mb_problem_headers:
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
  Accept-Encoding: "gzip, deflate, br"
  Accept-Language: "en-US,en;q=0.9"
  Cache-Control: "max-age=0"
  Connection: "keep-alive"
  Cookie: "__RequestVerificationToken=0hMmodpf1-AF5wYZgtyd2WVqcHuUbKXHXDKwko5Wde9f4udg5wxkbUFXc74lzZwqxK-La_oFm8TgTp5-tWeruttJUloEQ7-1rjzDAyboqYg1; _gid=GA1.2.2073676022.1688218032; _MoonBoard=8rrVN7l0-GEuSSchVVhNTUCEZDDeyI-4XXNwzWVHyF0pJHMKI2lcsGobG3omhgf2r-sQbuFtfQgKjx9l-TL5Ezus77qWaP8Xr1tT4ETMvSTrdwwNgXs-lNPsD47wmIravZp5Erdp8SUfazDDj2Wd1Q3C2u-vOoCIH5zQKHwaKK1MINgmU3FDPUSWV83L2TQJnUyz6XfNiPDqJUx_4uE_KSC-md9F8Haj672oyy6FebFFQYB2ypjHN8lG-1cAYxVDQNZzKLHff8errqjE3CAvzX5Ql6gAUMQtXI2q7N2ozAVo35wykLb24M1VNHOHA9envCFa-YYe-DDjAhsKawCjNnnA0DXq3NNn3o7ohFBtDjvl_PGKOTwf6gk_UADB58QN7VS29qc6DzIvNGmF-qzgjnL5RIWRhC5sZ3OAk07WR11tE_W2J_2OlMn_zf6O9cCTe4m4jtCcT3krkgeSHuBc3K6SlyQjdYZivnSzhDt9qPI-zQMzrYro9WsVt0K6BS4in3xBbLMEd1_gb6wwzKOhaziWnNIIfKmiWy672eDrkTU; _ga_FB4RWZ3KKE=GS1.1.1688222311.3.1.1688224058.0.0.0; _ga=GA1.2.1475750838.1688218032"
  Host: "www.moonboard.com"
  Sec-Fetch-Dest: "document"
  Sec-Fetch-Mode: "navigate"
  Sec-Fetch-Site: "none"
  Sec-Fetch-User: "?1"
  Upgrade-Insecure-Requests: "1"
  User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
  sec-ch-ua: "'Not.A/Brand';v='8', 'Chromium';v='114', 'Google Chrome';v='114'"
  sec-ch-ua-platform: "macOS"
